### ISSUE TITLE
Strange drag&drop behavior

### ISSUE THREAD

**Issue by inf3rno** [jake-phy/WindowIconList#100] opened 2015-08-21 06:02 UTC
I had this funny drag&drop glitch today: ![untitled](https://cloud.githubusercontent.com/assets/408911/9402202/5101cb38-47da-11e5-8e37-77da82e7ed98.png)  
I just wanted to switch back to firefox, when it started to drag the icon, and dropped it after several clicks on the middle of the screen. (ReArrange was off.) Removing and adding the applet did not solve it. It was still there after removal. Only a logout - login removed the icon and the gap between this and the other panels on the left side...

**Comment by inf3rno** [comment] 2015-08-21 17:42
1. I found out that this is because the panel reacts on onclick event and not on onmousedown. So if I am fast enough and pull out the cursor from the area, then it does not do anything. I think it would be better to bind the events to onmousedown, if it is possible.

**Comment by inf3rno** [comment] 2015-08-21 23:59
Moved the others to separated issues.

**Comment by inf3rno** [comment] 2015-08-24 10:07
I have the same bug today with another icon as well. alt+f2+restart solved.

**Comment by mbacou** [comment] 2015-08-31 20:26
Same here, I just installed a fresh Mint 17.2. Seems to be a mouse or trackpoint issue, every time I go to switch windows, I end up involuntarily dragging and/or pinning the app icon instead. I need to hit Esc then to release the icon. This renders the applet somewhat useless now.

**Comment by mbacou** [comment] 2015-08-31 20:32
Sorry this is a dup of https://github.com/jake-phy/WindowIconList/issues/92

**Comment by mbacou** [comment] 2015-09-01 15:37
Just want to mention changing the mouse "Drag-and-drop threshold (pixels)" to 4 (instead of the default 8) seems to help some, but icons are still sticking on occasion.

**Comment by inf3rno** [comment] 2015-09-01 15:56
@mbacou Interesting. By me this happens rarely, maybe once in 2-3 days...

**Comment by mbacou** [comment] 2015-09-01 23:20
I wonder if it's because I'm on small rather high PPI display (13.3", 1280×800, 113 ppi) and might need to adjust mouse or other settings correctly?

**Comment by jake-phy** [comment] 2015-12-05 06:42
Can you try with the latest git version?  I think this might be fixed.

**Comment by TurkeyMan** [comment] 2015-12-25 04:25
I used to experience this, but I can confirm I haven't seen it with latest.

**Comment by jake-phy** [comment] 2015-12-25 18:35
I think I will close this one.  Reopen if it happens again.

**Closed by jake-phy** 2015-12-25 18:35 UTC
Labels: Waiting for confirmation

**Comment by nyanpasu64** [comment] 2016-04-28 03:40
I just experienced the floating icon issue after a failed drag-and-drop.

**Comment by ghost** [comment] 2016-04-29 13:36
@jake-phy I no longer use gnome based desktop environments. Btw. I am not able to reopen for the others. :-)
