### ISSUE TITLE
Hovering and clicking on borders has no effect

### ISSUE THREAD

**Issue by BLiu1** [jake-phy/WindowIconList#79] opened 2015-02-23 02:43 UTC
When I'm navigating using this windows list, I find myself having to move my mouse up from the bottom borders of the icons in order for the window preview to show up. I am also unable to click on the bottom border to switch to that window.
Please fix this slight problem so that the borders act correctly.

**Comment by BLiu1** [comment] 2015-02-23 03:13
On further investigation, it appears that the borders of the icon do not extend all the way down to the last pixel. Look closely at the picture and you will see what I mean.
![workspace 1_002](https://cloud.githubusercontent.com/assets/6394967/6322311/738d3c92-badf-11e4-8250-719b0c4cdd9e.png)

**Comment by jake-phy** [comment] 2015-02-23 17:48
That is caused by the theme that you are using.   I am in the process of creating a style sheet that will allow developers to conform to this applet.  If you can give me the name of the theme  I'll see if I can contact his creator.

**Comment by BLiu1** [comment] 2015-02-24 01:13
I tried all of the default themes included in Linux Mint 17 Cinnamon and they all seem to have this effect. Furthermore, I went down the list of popular themes and the first ones that behaved correctly did not fit my taste. They were the Elementary Luna Mod and the ElementaryOS themes. All the others did not work.

**Comment by jake-phy** [comment] 2015-03-14 18:50
This should be fixed in the dev branch now.

**Closed** 2015-12-05 18:23 UTC
